
name: Release
on:
  schedule:
    - cron: "5 */12 * * *"
  push:
    branches:
      - "master"


jobs:
  Brave:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download Brave
      run: |
        curl https://api.github.com/repos/brave/brave-browser/releases/latest > /tmp/brave.json
        cat /tmp/brave.json| jq '.assets[].browser_download_url' | grep linux | grep -v symbols
        wget "$(cat /tmp/brave.json| jq -r '.assets[].browser_download_url' | grep linux | grep -v symbols)"
        VERSION="$(cat /tmp/brave.json| jq -r .tag_name)"
        echo "BRAVE_VERSION=$VERSION" >> $GITHUB_ENV
        if [[ -f *nightly*.zip ]]; then
          # this is a nightly release
          # mark as pre release
          echo "BRAVE_PRERELEASE=true" >> $GITHUB_ENV
          APPDIR=AppDir-nightly
          ICON=brave-browser-nightly
        elif [[ -f *dev*.zip ]]; then
          # this is a nightly release
          # mark as pre release
          echo "BRAVE_PRERELEASE=true" >> $GITHUB_ENV
          APPDIR=AppDir-dev
          ICON=brave-browser-dev
        else
          echo "BRAVE_PRERELEASE=false" >> $GITHUB_ENV
          APPDIR=AppDir
          ICON=brave-browser
        fi
        cp *.zip $APPDIR/.
        cd $APPDIR
        unzip *.zip && rm -rf *.zip
        ln -sr *.png "$ICON.png"
        cd ..

        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x *.AppImage
        echo "AppDir: $APPDIR"
        VERSION="$BRAVE_VERSION" ./appimagetool-x86_64.AppImage --comp gzip "$APPDIR" -n -u 'gh-releases-zsync|srevinsaju|Brave.AppImage|latest|Brave*.AppImage.zsync'
        mkdir dist
        mv Brave*.AppImage* dist/.
       

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: brave-continuous.AppImage
        path: 'dist'

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Brave AppImage ${{ env.BRAVE_VERSION }} Build
        automatic_release_tag: ${{ env.BRAVE_VERSION }}
        prerelease: ${{ env.BRAVE_PRERELEASE }}
        files: |
          dist/
        repo_token: ${{ secrets.GITHUB_TOKEN }}

